baseURL: "https://www.genderlibs.org/"   # Typically recommended to add a trailing slash
title: "Sino-Global Gender Diversity Library"
copyright: "Copyright © 2024-{year} GenderLibs. All Rights Reserved."
defaultContentLanguage: "en"
hasCJKLanguage: true  # If your site has Chinese (or other CJK) content, set true
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

module:
  imports:
    - path: github.com/razonyang/hugo-theme-bootstrap
#   proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
