en:
  languageName: English
  weight: 1

zh-hans:
  languageName: 简体中文
  weight: 2
  params:
    description: 传播多元性别文化，连接中国大陆与海外多元性别社群
    keywords: 'GenderLibs, Gender Diversity, Chinese-speaking, transgender, queer, lgbt'
    archive:
      dateFormat: 01-02
