main:
  - name: Github
    identifier: github
    url: https://github.com/project-polymorph/gender-library
    params:
      icon: '<i class="fas fa-fw fa-book"></i>'
  - name: 关于
    identifier: about
    url: /about
    params:
      icon: '<i class="fas fa-fw fa-gender"></i>'
